### ISSUE TITLE
Which optimizer rules are applied for this simple query

### ISSUE THREAD

**Issue by bithw1** [bartosz25/spark-playground#1]
Hi, @bartosz25 

I have following simple query, but I can't figure out which optimization rules are applied.

```
  test("optimization rule test") {
    //CollapseProject?
    //PushDownPredicates?
   //exclude the CollapseProject rule doesn't work
    val spark = SparkSession.builder().master("local").appName("SparkSQLTest1-1")./*config("spark.sql.optimizer.excludedRules", CollapseProject.ruleName).*/
    .getOrCreate()
    import spark.implicits._
    Seq(
      ("John", 23, "A"), ("John", 23, "B"), ("Jack", 21, "Y"), ("Jack", 21, "X"), ("Mike", 31, "E"), ("Mike", 31, "F"), ("Mike", 44, "F"), ("John", 27, "A")
    ).toDF("name", "age", "level").createOrReplaceTempView("t")
    val df = spark.sql(
      """
      select name from (
          select name,age, level from t
      ) where age > 30
      """.stripMargin(' '))
    df.explain(true)
    df.show(truncate = false, numRows = 100)

  }


```

The analyzed and optimized plan are as follows:

```
== Analyzed Logical Plan ==
name: string
Project [name#10]
+- Filter (age#11 > 30)
   +- SubqueryAlias `__auto_generated_subquery_name`
      +- Project [name#10, age#11, level#12]
         +- SubqueryAlias `t`
            +- Project [_1#3 AS name#10, _2#4 AS age#11, _3#5 AS level#12]
               +- LocalRelation [_1#3, _2#4, _3#5]

== Optimized Logical Plan ==
Project [name#10]
+- Filter (age#11 > 30)
   +- LocalRelation [name#10, age#11, level#12]


```

The optimized plan is obsious,because the simple sql can be rewritten as 

```
 select name from t where age > 30
```

But, I look though and try the optimizer rules, I didn't find which rules apply for this case,

could you please help me take a look? Thanks!

**Comment by bithw1** [comment]
After investigation， I think 3 rules apply here.

1. PushDownPredicates
2. ColumnPruning
3. CollapseProject

I think `CollapseProject` will be used to eliminate the redundant `project` operator, but in my code, I have excluded `CollapseProject` rule, but the `project` is still eliminated ,not sure whether other rules apply here.

**Comment by bartosz25** [comment]
Hi @bithw1 

Long time no see ;) 

When it comes to the rules, the easiest way is to look at the `=== Applying Rule ... ===` logs, as for example:
```
=== Applying Rule org.apache.spark.sql.catalyst.expressions.codegen.package$ExpressionCanonicalizer$CleanExpressions ===
!staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))._1, true, false, true) AS _1#0   staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))._1, true, false, true)
!+- staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))._1, true, false, true)        +- knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))._1
!   +- knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))._1                                                                                                                 +- knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))
!      +- knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))                                                                                                                    +- assertnotnull(input[0, scala.Tuple3, true])
!         +- assertnotnull(input[0, scala.Tuple3, true])                                                                                                                                  +- input[0, scala.Tuple3, true]
!            +- input[0, scala.Tuple3, true]                                                                                                                                     
            (org.apache.spark.sql.catalyst.rules.PlanChangeLogger:68)

```

After running your code snippet, I can see the:

> === Applying Rule org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation ===
> === Applying Rule org.apache.spark.sql.catalyst.optimizer.RemoveNoopOperators ===
> === Applying Rule org.apache.spark.sql.catalyst.optimizer.Optimizer$FinishAnalysis ===
> === Applying Rule org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveAliases ===
> === Applying Rule org.apache.spark.sql.catalyst.analysis.ResolveTimeZone ===
> === Applying Rule org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation ===
> === Applying Rule org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations ===
> === Applying Rule org.apache.spark.sql.catalyst.expressions.codegen.package$ExpressionCanonicalizer$CleanExpressions ===

Best,
Bartosz.

**Comment by bithw1** [comment]
Hi @bartosz25 ,thanks for your helpful answers!

Yes, nice to get in touch again,:-).  It is about 2 years that I have been working on projects not related to spark. Now I am back to recall the knowledge, starting from your great blog posts, :-)
